#+TITLE:       org-webpage 的配置与使用
#+AUTHOR:      皐月中二
#+EMAIL:       kuangdash@163.com
#+DATE:        2015-04-29 周三

# #+URI:         /blog/%y/%m/%d/%t/ Or /blog/%t/
#+KEYWORDS:    org-webpage, org-page, org-mode, git
#+TAGS:        org-webpage, org-page, org-mode, git
#+DESCRIPTION: The use of static site generator based on emacs git org-mode

#+LANGUAGE:    zh-CN
#+OPTIONS:     H:4 num:nil toc:t \n:nil ::t |:t ^:nil -:nil f:t *:t <:t

#+BEGIN_HTML
<p class="center">
<a href="https://github.com/emacs-china/emacs-china.github.io/edit/source/blog/KuangDash/org-webpage.org">点我修改</a><br/>
</p>
#+END_HTML

* org-page 和 org-webpage 的区别
在看本文之前，各位可以先参考我前面写的 [[http://emacs-china.org/blog/2015/04/15/org-page%25E7%259A%2584%25E9%2585%258D%25E7%25BD%25AE%25E4%25B8%258E%25E4%25BD%25BF%25E7%2594%25A8/][关于 org-page 的介绍]] 。其中的一部分命令和 _需要 hack 解决的问题_[fn:1] ，在 org-webpage 里面也是有效的。注意：org-page 里面带 =op/= 前缀的命令在 org-webpage 里面就会变成 =owp/= 了。

org-webpage 的着重点在于 *多站点的管理* ，这导致了它在设置以及其他方面和 org-page （着重点在个人博客）有所不同。

想要仔细了解 org-webpage 的同学可以直接阅读 org-webpage 的 [[http://tumashu.github.io/org-webpage/][项目主页]] （英语）。这里我将谈一谈我个人用它设置 emacs-china 主站点的经验。

* org-webpage 在 emacs-china 上的设置
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/github/org-webpage")
  (require 'org-webpage)
  (add-to-list 'owp/project-config-alist
               `("emacs-china"
                 :repository-directory "~/github/emacs-china.github.io"
                 :site-domain "http://emacs-china.github.io/"
                 :site-main-title "EMACS-CHINA"
                 :site-sub-title "=============>集思广益"
                 :theme (emacs_love)
                 :summary (("tags" :tags) ("authors" :authors))
                 :source-browse-url ("Github" "https://github.com/emacs-china")
                 :personal-disqus-shortname "emacs-china"
                 :personal-duoshuo-shortname "emacs-china"
                 :confound-email nil
                 :web-server-docroot "~/webRoot/emacs-china.github.io"
                 :web-server-port 5432))
#+END_SRC

直接上代码的好处就是：如果你看的懂代码，那就不用看我下面的啰嗦了。 =if= 你看不懂各个选项的意义，那么：

开头的 =load-path= 和 =require= 可自行了解，不用多谈。下面说下 =owp/project-config-alist= 里面的 =“emacs-china”= 项下面各个键值对的意义：

+ =:repository-directory= :: 你的 project 所在的目录。
+ =:site-domain= :: 你的站点域名。
+ =:site-xxx-title= :: 站点标语一类的。
+ =:theme= :: 你的 project 所使用的主题，这里使用 [[https://github.com/kuangdash/owp_emacs_love][emacs_love]] _主题_[fn:2]。由于 emacs-china 的 source branch 下的 themes 文件夹内已经包含了该主题，所以 emacs-china 可以无需设置，直接用 =owp/do-publication= 进行发布。
+ =:summary= :: 你的导航栏可拉出来的选项。
+ =:source-browse-url= :: 看到 “Github” 的话，也应该了解。
+ =:personal-disqus-shortname= :: 和下面的 =:personal-duoshuo-shortname= 一样，用于设置评论系统。
+ =:confound-email= :: 该值为 boolean 型；为t时，站点下方邮件地址为防垃圾邮件模式；为nil时，站点下方邮件地址正常显示。（防恶意邮件的功能）
+ =:web-server-docroot= :: 这里放用于测试站点的目录，org-webpage 集成了一个用于测试的小型服务器。
+ =:web-server-port= :: 这里是服务器的服务端口。

* 关于 org-webpage 的其他功能
org-webpage 还支持 “主题继承”，能让多站点管理时的主题修改轻松很多。这里只点一下要点：

#+BEGIN_SRC emacs-lisp
:theme (haru emacs_love)
#+END_SRC

=haru= 是在 =emacs_love= 上修改的主题。实际上 =:theme= 对应的括号里可以有很多主题，形成一个 _主题链_[fn:3] 。

* Footnotes

[fn:1] 请 [[http://emacs-china.org/blog/2015/04/15/org-page%25E7%259A%2584%25E9%2585%258D%25E7%25BD%25AE%25E4%25B8%258E%25E4%25BD%25BF%25E7%2594%25A8/#orgheadline8][点击这里跳转到具体问题]] （悬停卡片里无法点击？点右上标）

[fn:2] 下载（ =git clone= ）下来后放在 org-webpage 的 path 所在目录的 themes 目录下面，你在那将见到几个主题，对比一下就了解用法了。

[fn:3] 最开头的最优先。

