#+title: 欢迎来到 emacs-china
#+author: emacs-china
#+email: emacs-china@googlegroups.com

#+URI:     /
#+OPTIONS:     H:4 num:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t

#+ATTR_HTML: :class center
[[./assets/dragon2.svg]]

#+BEGIN_HTML
<p class="center">
<a href="https://github.com/emacs-china/emacs-china.github.io/edit/source/index.org">点我修改</a><br/>
</p>
#+END_HTML

* emacs-china 项目列表
以下所有项目均可在 [[https://github.com/emacs-china]] 上找到。本站点对应项目是 [[https://github.com/emacs-china/emacs-china.github.io][emacs-china.github.io]] 。
** 新人入门资料

这里是一些新人入门的中文资料。

*** hello-emacs
darksun 同学所写的关于 emacs 的中文笔记，十分详实，看的出作者是个优等生。欢迎拍砖（即是向该项目提交patch，改进它）。

** 字体与输入法

emacs自带各国输入法，当然也包括中文。

*** chinese-fonts-setup
从 tumashu 先生那 fork 过来的项目，用于解决 org-mode 表格中的中文字体无法对齐的问题，使 org-mode 中的中文变得十分美观。

*** chinese-pyim
从 tumashu 先生那 fork 过来的项目，一个 emacs 中的中文拼音输入法，相对 emacs 自带的那些中文输入法，使用起来十分便捷。

** 静态站点生成器

用 emacs 写 blog，乐趣多多。

*** org-page
Kelvin Hu 先生所写的静态站点生成器，基于 emacs、 org-mode 和 git （git 功能的添加使它支持 增量式的文档发布功能） ，简约美观，设计合理。

*** org-webpage
tumashu 先生在 Kelvin Hu 先生的 org-page 基础上所写的 _静态站点生成器_[fn:1] 。相较 org-page ，org-webpage 更适合多站点管理时使用，本站点即是由它生成。

* 中文资料
在本站点的 Blog 目录下面，可以在 Tags 下面按标签索引文件，也可使用 search 框。

所有文档的 org-mode 原文件都在 emacs-china.github.io 项目的 source branch 下，欢迎改进（请好好学习 git 和 github 的用法）。

另外，欢迎各位用 org-mode 文件投稿，我们不会修改一篇文章的 =author= 和 =email= 。（请好好学习 org-mode 的用法，hello-emacs 中有 darksun  写的 org-manual （ org-mode 的中文使用手册））

* 各种各样的联系方式
+ weibo :: ……
+ IRC :: ……
+ email :: 点击页面最底下的 emacs-china 链接
+ QQ群 :: ……
+ gitter(内部使用) :: [[https://gitter.im/emacs-china][点击我]]
期待和各位 emacs 中文用户的交流！

* Footnotes

[fn:1] org-webpage 在 org-page 上添加了主题继承功能，但该观点未被 Kelvin Hu 采纳，后来独立出该分支，并集成了站点本地测试的功能。

